url:
    deploy-url:
        pattern: /$YAMLURL/url/(.*)               # Any URL under this directory
        handler: FileHandler                      # is rendered as a FileHandler
        kwargs:
            path: $YAMLPATH/template.html         # Using this template
            transform:
                "template.html":
                    # Convert to a Tornado template
                    # GUIDE_ROOT is the absolute URL to the Gramex guide
                    function: template(content, GUIDE_ROOT="$GUIDE_ROOT")
    gramex-config-file:
        pattern: /$YAMLURL/config                 # Map config under current URL
        handler: FileHandler
        kwargs:
            path: $GRAMEXPATH/gramex.yaml         # to the core Gramex config ile
