# Theme configurations
# --------------------

# Color variables.
# parameter: {title: display-name, default: default-color}
color:
    primary:    {title: Primary,         default: '#007bff'}
    secondary:  {title: Secondary,       default: '#868e96'}
    success:    {title: Success,         default: '#28a745'}
    info:       {title: Info,            default: '#17a2b8'}
    warning:    {title: Warning,         default: '#ffc107'}
    danger:     {title: Danger,          default: '#dc3545'}
    light:      {title: Light,           default: '#f8f9fa'}
    dark:       {title: Dark,            default: '#343a40'}
    body-bg:    {title: Body background, default: '#ffffff'}
    body-color: {title: Body color,      default: '#212529'}

# Other varibles:
# font-size-base
# font-size-lg
# font-size-sm

# parameter: {title: display-name, default: enabled-or-not, options: sass-variables}
toggle:
    enable-rounded:
      title: Rounded
      default: 'on'
      options:
        'on': {enable-rounded: "true"}
        '': {enable-rounded: "false"}
    enable-shadows:
      title: Shadows
      default: ''
      options:
        'on': {enable-shadows: "true"}
        '': {enable-shadows: "false"}
    enable-gradients:
      title: Gradients
      default: ''
      options:
        'on': {enable-gradients: "true"}
        '': {enable-gradients: "false"}
    enable-transitions:
      title: Transitions
      default: 'on'
      options:
        'on': {enable-transitions: "true"}
        '': {enable-transitions: "false"}
    enable-print-styles:
      title: Print styles
      default: 'on'
      options:
        'on': {enable-print-styles: "true"}
        '': {enable-print-styles: "false"}

font:
  font-family-base:
    title: Body font
    default: ''
    options:
      '': Default
      calibri: Calibri
      helvetica: Helvetica
      open-sans: Open Sans
      roboto: Roboto
      segoe-ui: Segoe UI
      lato: Lato
      anton: Anton
  headings-font-family:
    title: Heading font
    default: ''
    options:
      '': Default
      calibri: Calibri
      helvetica: Helvetica
      open-sans: Open Sans
      roboto: Roboto
      segoe-ui: Segoe UI
      century-gothic: Century Gothic
      roboto-condensed: Roboto Condensed
      open-sans-condensed: Open Sans Condensed
      lato: Lato
      anton: Anton

theme:
  Bootstrap: {}

  Brand Book:
    primary: '#20186F'
    secondary: '#784894'
    success: '#8AB545'
    warning: '#D06027'
    danger: '#83153E'
    info: '#1599C4'
    dark: '#000000'
    light: '#A7A9AB'

  Material:
    primary: '#2196F3'
    secondary: '#9E9E9E'
    success: '#4CAF50'
    warning: '#FFEB3B'
    danger: '#F44336'
    info: '#00BCD4'

  Metro:
    primary: '#0050ef'
    secondary: '#647687'
    success: '#60a917'
    warning: '#f0a30a'
    danger: '#e51400'
    info: '#aa00ff'
