# Theme configurations
# --------------------

# Color variables.
# parameter: {title: display-name, default: default-color}
color:
    primary:    {title: Primary,         default: '#007bff'}
    secondary:  {title: Secondary,       default: '#868e96'}
    success:    {title: Success,         default: '#28a745'}
    info:       {title: Info,            default: '#17a2b8'}
    warning:    {title: Warning,         default: '#ffc107'}
    danger:     {title: Danger,          default: '#dc3545'}
    light:      {title: Light,           default: '#f8f9fa'}
    dark:       {title: Dark,            default: '#343a40'}
    body-bg:    {title: Body background, default: '#ffffff'}
    body-color: {title: Body color,      default: '#212529'}
    color1:     {title: Color 1,         default: '#6f42c1'}
    color2:     {title: Color 2,         default: '#6610f2'}
    color3:     {title: Color 3,         default: '#e83e8c'}
    color4:     {title: Color 4,         default: '#ffc107'}
    color5:     {title: Color 5,         default: '#20c997'}
    color6:     {title: Color 6,         default: '#dee2e6'}

# Other variables:
# font-size-base
# font-size-lg
# font-size-sm

# parameter: {title: display-name, default: enabled-or-not, options: sass-variables}
toggle:
    enable-rounded:
      title: Rounded
      default: 'true'
    enable-shadows:
      title: Shadows
      default: 'false'
    enable-gradients:
      title: Gradients
      default: 'false'
    enable-transitions:
      title: Transitions
      default: 'true'
    enable-responsive-font-sizes:
      title: Responsive fonts
      default: 'false'
    enable-print-styles:
      title: Print styles
      default: 'true'

font:
  font-family-base:
    title: Body font
    default: ''
    options:
      '': Default
      calibri: Calibri
      helvetica: Helvetica
      open-sans: Open Sans
      roboto: Roboto
      segoe-ui: Segoe UI
      lato: Lato
      anton: Anton
      montserrat: Montserrat
  headings-font-family:
    title: Heading font
    default: ''
    options:
      '': Default
      calibri: Calibri
      helvetica: Helvetica
      open-sans: Open Sans
      roboto: Roboto
      segoe-ui: Segoe UI
      century-gothic: Century Gothic
      roboto-condensed: Roboto Condensed
      open-sans-condensed: Open Sans Condensed
      lato: Lato
      anton: Anton
      montserrat: Montserrat

fontsize:
    font-size-base: {title: Base size,  default: '1rem'}
    h6-font-size:   {title: H6 size,    default: '1rem'}
    h5-font-size:   {title: H5 size,    default: '1.25rem'}
    h4-font-size:   {title: H4 size,    default: '1.5rem'}
    h3-font-size:   {title: H3 size,    default: '1.75rem'}
    h2-font-size:   {title: H2 size,    default: '2rem'}
    h1-font-size:   {title: H1 size,    default: '2.5rem'}

theme:
  Bootstrap: {}

  Brand Book:
    primary: '#20186F'
    secondary: '#784894'
    success: '#8AB545'
    warning: '#D06027'
    danger: '#83153E'
    info: '#1599C4'
    dark: '#000000'
    light: '#A7A9AB'

  Material:
    primary: '#2196F3'
    secondary: '#9E9E9E'
    success: '#4CAF50'
    warning: '#FFEB3B'
    danger: '#F44336'
    info: '#00BCD4'

  Metro:
    primary: '#0050ef'
    secondary: '#647687'
    success: '#60a917'
    warning: '#f0a30a'
    danger: '#e51400'
    info: '#aa00ff'
