import:
  ui:
    path: $GRAMEXAPPS/ui/gramex.yaml    # Import the UI components
    YAMLURL: $YAMLURL/ui/               # ... at this URL

url:
  gallery-data:
    pattern: /$YAMLURL/data/(.*)
    handler: FileHandler
    kwargs:
      path: $YAMLPATH/data/
      headers:
        Access-Control-Allow-Origin: '*'

  towns-data:
    pattern: /$YAMLURL/towns
    handler: FormHandler
    kwargs:
      url: $YAMLPATH/data/towns.xlsx
      headers:
        Access-Control-Allow-Origin: '*'
