fonts:
    calibri:             {stack: 'Calibri, Candara, Segoe, "Segoe UI", Optima, Arial, sans-serif'}
    helvetica:           {stack: '"Helvetica Neue", Helvetica, Arial, sans-serif'}
    open-sans:           {stack: '"Open Sans", sans-serif', google: Open+Sans}
    lato:                {stack: 'Lato, sans-serif', google: Lato}
    anton:               {stack: 'Anton, sans-serif', google: Anton}
    roboto:              {stack: 'Roboto, sans-serif', google: Roboto}
    segoe-ui:            {stack: '"Segoe UI", "Open Sans", sans-serif', google: Open+Sans}
    montserrat:          {stack: 'Montserrat, sans-serif', google: Montserrat}
    century-gothic:      {stack: '"Century Gothic", CenturyGothic, AppleGothic, sans-serif'}
    roboto-condensed:    {stack: '"Roboto Condensed", sans-serif', google: Roboto+Condensed}
    open-sans-condensed: {stack: '"Open Sans Condensed", sans-serif', google: 'Open+Sans+Condensed:300'}

defaults:
    color1: '#6f42c1'   # $purple
    color2: '#6610f2'   # $indigo
    color3: '#e83e8c'   # $pink
    color4: '#ffc107'   # $yellow
    color5: '#20c997'   # $teal
    color6: '#dee2e6'   # $gray-300
