fonts:
    calibri:             {stack: 'Calibri, Candara, Segoe, "Segoe UI", Optima, Arial, sans-serif'}
    helvetica:           {stack: '"Helvetica Neue", Helvetica, Arial, sans-serif'}
    open-sans:           {stack: '"Open Sans", sans-serif', google: Open+Sans}
    lato:                {stack: 'Lato, sans-serif', google: Lato}
    anton:               {stack: 'Anton, sans-serif', google: Anton}
    roboto:              {stack: 'Roboto, sans-serif', google: Roboto}
    segoe-ui:            {stack: '"Segoe UI", "Open Sans", sans-serif', google: Open+Sans}
    century-gothic:      {stack: '"Century Gothic", CenturyGothic, AppleGothic, sans-serif'}
    roboto-condensed:    {stack: '"Roboto Condensed", sans-serif', google: Roboto+Condensed}
    open-sans-condensed: {stack: '"Open Sans Condensed", sans-serif', google: 'Open+Sans+Condensed:300'}
